keys:
  - &joerg age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &lassulus age1eq0e6uhjj2tja8v338tkdz8ema2aw5anpuyaq2uru7rt4lq7msyqqut6m2
creation_rules:
  - path_regex: targets/.*/terraform.tfstate$
    key_groups:
    - age:
      - *joerg
      - *lassulus
