name: checks
on:
  pull_request:
  push:
    branches: main
jobs:
  test:
    runs-on: nix
    steps:
      - run: sleep 99999
      - uses: actions/checkout@v3
      - run: nix run --refresh github:Mic92/nix-fast-build -- --no-nom
