{ self, config, ... }:
{
  imports = [
    ./borgbackup.nix
    ./clan-merge.nix
    ./gitea
    ./goaccess.nix
    ./harmonia.nix
    ./homepage.nix
    ./postfix.nix
    ./jobs.nix
    ./matrix-synapse.nix
    ../dev.nix
    self.inputs.clan-core.clanModules.zt-tcp-relay
  ];

  # we need to keep the rsa key on top of the ed25519 key generated by clan,
  # because other clients will refuse to connect to the server.
  services.openssh.hostKeys = [
    {
      path = config.sops.secrets.ssh_host_rsa_key.path;
      type = "rsa";
    }
  ];

  services.cloud-init.xfs.enable = true;
}
